"""Framework-free QuantOps market-risk engine."""

from .alignment import AlignedSeries, align_series
from .backtesting import (
    VaRBacktestObservation,
    VaRBacktestResult,
    backtest_var,
    kupiec_proportion_of_failures,
    rolling_historical_var_backtest,
    var_exception_backtest,
)
from .concentration import concentration, herfindahl_hirschman
from .contributions import volatility_contributions
from .correlation import correlation_matrix
from .covariance import portfolio_variance, sample_covariance_matrix
from .drawdown import maximum_drawdown
from .evidence import (
    EvidenceItem,
    EvidenceManifest,
    build_evidence_manifest,
    evidence_item,
)
from .exceptions import (
    CurrencyMismatchError,
    DuplicateInstrumentError,
    InsufficientDataError,
    InvalidInputError,
    MissingDataError,
    NonPositivePriceError,
    ReconciliationError,
    RiskEngineError,
)
from .expected_shortfall import (
    expected_shortfall,
    historical_expected_shortfall,
    parametric_expected_shortfall,
)
from .methodology import (
    METHODOLOGY_VERSION,
    MethodologyMetadata,
    methodology_metadata,
)
from .returns import arithmetic_returns, calculate_returns, log_returns
from .scenarios import (
    SYSTEM_SCENARIOS,
    AssetClassShock,
    CorrelationOverride,
    FXShock,
    InstrumentPriceShock,
    ScenarioDefinition,
    ScenarioPosition,
    ScenarioPositionResult,
    ScenarioRun,
    VolatilityMultiplier,
    run_scenario,
    system_scenario,
)
from .types import (
    AlignmentPolicy,
    CalculationStatus,
    ConcentrationEstimate,
    ContributionEstimate,
    CorrelationEstimate,
    CovarianceEstimate,
    DrawdownEstimate,
    ExpectedShortfallEstimate,
    MissingDataPolicy,
    PortfolioValuation,
    PositionInput,
    PositionValuation,
    ReturnMethod,
    ReturnSeries,
    RiskEstimate,
    VolatilityContribution,
    VolatilityEstimate,
)
from .valuation import normalize_currency, value_portfolio, value_position
from .var import empirical_quantile, historical_var, parametric_var, parametric_var_from_returns
from .volatility import rolling_sample_volatility, sample_volatility

__all__ = [
    "METHODOLOGY_VERSION",
    "SYSTEM_SCENARIOS",
    "AlignedSeries",
    "AlignmentPolicy",
    "AssetClassShock",
    "CalculationStatus",
    "ConcentrationEstimate",
    "ContributionEstimate",
    "CorrelationEstimate",
    "CorrelationOverride",
    "CovarianceEstimate",
    "CurrencyMismatchError",
    "DrawdownEstimate",
    "DuplicateInstrumentError",
    "EvidenceItem",
    "EvidenceManifest",
    "ExpectedShortfallEstimate",
    "FXShock",
    "InstrumentPriceShock",
    "InsufficientDataError",
    "InvalidInputError",
    "MethodologyMetadata",
    "MissingDataError",
    "MissingDataPolicy",
    "NonPositivePriceError",
    "PortfolioValuation",
    "PositionInput",
    "PositionValuation",
    "ReconciliationError",
    "ReturnMethod",
    "ReturnSeries",
    "RiskEngineError",
    "RiskEstimate",
    "ScenarioDefinition",
    "ScenarioPosition",
    "ScenarioPositionResult",
    "ScenarioRun",
    "VaRBacktestObservation",
    "VaRBacktestResult",
    "VolatilityContribution",
    "VolatilityEstimate",
    "VolatilityMultiplier",
    "align_series",
    "arithmetic_returns",
    "backtest_var",
    "build_evidence_manifest",
    "calculate_returns",
    "concentration",
    "correlation_matrix",
    "empirical_quantile",
    "evidence_item",
    "expected_shortfall",
    "herfindahl_hirschman",
    "historical_expected_shortfall",
    "historical_var",
    "kupiec_proportion_of_failures",
    "log_returns",
    "maximum_drawdown",
    "methodology_metadata",
    "normalize_currency",
    "parametric_expected_shortfall",
    "parametric_var",
    "parametric_var_from_returns",
    "portfolio_variance",
    "rolling_historical_var_backtest",
    "rolling_sample_volatility",
    "run_scenario",
    "sample_covariance_matrix",
    "sample_volatility",
    "system_scenario",
    "value_portfolio",
    "value_position",
    "var_exception_backtest",
    "volatility_contributions",
]
